### PR TITLE
Fix migrating issues between repositories with the same name.

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
The extension fails to migrate issues between repositories with the same name, in different organisations.

### CODE REVIEW

**Comment by johnmurphy01** [comment]
Nice find! I will review

**Comment by maciejwalkowiak** [comment]
Kamino is a god send! I am migrating https://github.com/spring-cloud/spring-cloud-aws/ to https://github.com/awspring/spring-cloud-aws/ and cherry pick issues - your extension makes my life much easier!

**Review by johnmurphy01 — APPROVED** [review]
Changes look good! I wasn't thinking about the same repo name in a different organization, so this is a good change

**Comment by johnmurphy01** [comment]
> Kamino is a god send! I am migrating https://github.com/spring-cloud/spring-cloud-aws/ to https://github.com/awspring/spring-cloud-aws/ and cherry pick issues - your extension makes my life much easier!

Thank you for the kind words! I will get this into a release asap

**Pull request merged**
