### PR TITLE
Enhancement/145 disable comments

### LINKED ISSUE #145: Disable comment on clone
It would be nice if we could clone an issue, without commenting.
I dont like spamming the upstream of a project because I copy some issues.

### PR DESCRIPTION
**Pull request by johnmurphy01**
Resolves #145 

- Add an option in settings that, when checked, will disable automatic comments on the original issue

### CODE REVIEW

**Comment by JamesNewton** [comment]
Hey, thanks for the fast response... I'm trying to get the installed version in Chrome to update, but not having much luck... it says it's updating but then just sits there... times 10 minutes so far. Any thoughts?

**Comment by JamesNewton** [comment]
Oh, I see the issue... it hasn't updated to the new version in the chrome extensions store. Is that normal? Probably a delay until it's re-accepted.

**Comment by johnmurphy01** [comment]
I just deployed the new version. Sorry my timetable of this morning didn't work out as expected. Keep checking, it should update soon

**Comment by JamesNewton** [comment]
Still don't see it... hopefully Monday.

**Comment by johnmurphy01** [comment]
Just checked and it has been deployed. Let me know if it doesn't work for you!

**Comment by JamesNewton** [comment]
Thank you John! It worked just fine and I was able to get the rest of the issues transferred without spamming everyone.

**Comment by johnmurphy01** [comment]
Awesome! Glad to hear

**Pull request merged**
